export const environment = {
  production: false,
  apiUrl: 'http://localhost:3000/api',
  featureFlag: true,
  version: '1.0.0',
  logging: {
    level: 'debug',
    enableConsole: true,
    enableFile: false,
  },
  analytics: {
    enabled: true,
    trackingId: 'UA-12345678-1',
    anonymizeIp: true,
  },
  featureToggles: {
    newFeature: false,
    betaAccess: true,
  },
  cache: {
    enabled: true,
    ttl: 3600, // Time to live in seconds
  },
  security: {
    csrfToken: 'your-csrf-token',
    cspPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline';",
    xssProtection: true,
    contentTypeOptions: 'nosniff',
  },
  apiKeys: {
    googleMaps: 'YOUR_GOOGLE_MAPS_API_KEY',
    stripe: 'YOUR_STRIPE_API_KEY',
    sentry: 'YOUR_SENTRY_API_KEY',
    openWeather: 'YOUR_OPEN_WEATHER_API_KEY',
    firebase: {
      apiKey: 'YOUR_FIREBASE_API_KEY',
      authDomain: 'YOUR_FIREBASE_AUTH_DOMAIN',
      projectId: 'YOUR_FIREBASE_PROJECT_ID',
      storageBucket: 'YOUR_FIREBASE_STORAGE_BUCKET',
      messagingSenderId: 'YOUR_FIREBASE_MESSAGING_SENDER_ID',
      appId: 'YOUR_FIREBASE_APP_ID',
    },
    aws: {
        accessKeyId: 'YOUR_AWS_ACCESS_KEY_ID',
        secretAccessKey: 'YOUR_AWS_SECRET_ACCESS_KEY',
        region: 'YOUR_AWS_REGION',
    },
    azure: {
        clientId: 'YOUR_AZURE_CLIENT_ID',
        tenantId: 'YOUR_AZURE_TENANT_ID',
        clientSecret: 'YOUR_AZURE_CLIENT_SECRET',
        subscriptionId: 'YOUR_AZURE_SUBSCRIPTION_ID',
        resourceGroup: 'YOUR_AZURE_RESOURCE_GROUP',
        storageAccount: 'YOUR_AZURE_STORAGE_ACCOUNT',
        sqlServer: 'YOUR_AZURE_SQL_SERVER',
        sqlDatabase: 'YOUR_AZURE_SQL_DATABASE',
        appService: 'YOUR_AZURE_APP_SERVICE',
        functionApp: 'YOUR_AZURE_FUNCTION_APP',
        keyVault: 'YOUR_AZURE_KEY_VAULT',
        cosmosDb: 'YOUR_AZURE_COSMOS_DB',
        serviceBus: 'YOUR_AZURE_SERVICE_BUS',
        eventHub: 'YOUR_AZURE_EVENT_HUB',
        logicApps: 'YOUR_AZURE_LOGIC_APPS',
        appInsights: 'YOUR_AZURE_APP_INSIGHTS',
        containerRegistry: 'YOUR_AZURE_CONTAINER_REGISTRY',
        kubernetesService: 'YOUR_AZURE_KUBERNETES_SERVICE',
        cognitiveServices: {
            vision: 'YOUR_AZURE_COGNITIVE_SERVICES_VISION',
            speech: 'YOUR_AZURE_COGNITIVE_SERVICES_SPEECH',
            language: 'YOUR_AZURE_COGNITIVE_SERVICES_LANGUAGE',
            decision: 'YOUR_AZURE_COGNITIVE_SERVICES_DECISION',
            search: 'YOUR_AZURE_COGNITIVE_SERVICES_SEARCH',
            textAnalytics: 'YOUR_AZURE_COGNITIVE_SERVICES_TEXT_ANALYTICS',
            personalizer: 'YOUR_AZURE_COGNITIVE_SERVICES_PERSONALIZER',
            anomalyDetector: 'YOUR_AZURE_COGNITIVE_SERVICES_ANOMALY_DETECTOR',
            metrics: 'YOUR_AZURE_COGNITIVE_SERVICES_METRICS',
            contentModerator: 'YOUR_AZURE_COGNITIVE_SERVICES_CONTENT_MODERATOR',
            face: 'YOUR_AZURE_COGNITIVE_SERVICES_FACE',
        }
    },
    github: {
        clientId: 'YOUR_GITHUB_CLIENT_ID',
        clientSecret: 'YOUR_GITHUB_CLIENT_SECRET',
        redirectUri: 'YOUR_GITHUB_REDIRECT_URI',
    },
    twitter: {
        apiKey: 'YOUR_TWITTER_API_KEY',
        apiSecretKey: 'YOUR_TWITTER_API_SECRET_KEY',
        accessToken: 'YOUR_TWITTER_ACCESS_TOKEN',
        accessTokenSecret: 'YOUR_TWITTER_ACCESS_TOKEN_SECRET',
    },
  },
}